class GCM_Flag():
    FLAG_CLIENT_CONNECTION = False
    FLAG_CLIENT_CLOSED = False
    FLAG_CLIENT_OPEN = False
    FLAG_SERVER_OPEN = False
    FLAG_SERVER_CLOSED = False
    FLAG_SERVER_THREAD_OPEN = False
    FLAG_PROGRAM_SHUTDOWN = False
    FLAG_DATABASE_IS_ON = False
