#ifndef TCPMANAGER_GLOBAL_H
#define TCPMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPMANAGER_LIBRARY)
#  define TCPMANAGER_EXPORT Q_DECL_EXPORT
#else
#  define TCPMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPMANAGER_GLOBAL_H
