class RCM_Flag():
    FLAG_AUTO_MODE = False
    FLAG_CLIENT_CONNECTION = False
    FLAG_CLIENT_CLOSED = False
    FLAG_CLIENT_OPEN = False
    FLAG_CUT_RECEIVE = False
    FLAG_DATABASE_IS_ON = False
    FLAG_EMERGENCY = False
    FLAG_ENABLE_TO_MOVE_FIXGUN = False
    FLAG_FIRST_MOTION = False
    FLAG_RECV_FROM_NSG_STOP = False
    FLAG_GUN_SPRAYING_ON = False
    FLAG_HOME = False
    FLAG_MOTION_EXECUTED = False
    FLAG_MOTION_REPEAT = False
    FLAG_OPEN = False
    FLAG_PROGRAM_SHUTDOWN = False
    FLAG_RECV_FROM_NSG_START = False
    FLAG_RECV_OK = False
    FLAG_ROBOT_DISCONNECTED = False
    FLAG_ROBOT_MOTION_DONE = False
    FLAG_ROBOT_START = False
    FLAG_SEND_ANGLE_DATA_TO_ROBOT = False
    FLAG_SERVER_CLOSED = False
    FLAG_SERVER_EMS_MSG = False
    FLAG_SERVER_OPEN = False
    FLAG_SERVER_THREAD_OPEN = False
    FLAG_SIMULATION = False
    FLAG_START_SENDING_JOINT_ANGLE_DATA = False
    FLAG_THREAD_SENDING_STATE = False
    FLAG_THREAD_STOP = False














